CREATE TYPE "ServiceVariant" AS ENUM ('STANDARD', 'EXTENDED');

ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'AWIT_NG_HIMNO';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'TIPAN_PAHAYAG';

ALTER TABLE "WorshipService"
ADD COLUMN "serviceVariant" "ServiceVariant" NOT NULL DEFAULT 'STANDARD';
