import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

export function runServiceTemplateRenderingTests() {
  const route = readFileSync(join(process.cwd(), "src", "app", "api", "services", "route.ts"), "utf8");
  const page = readFileSync(join(process.cwd(), "src", "components", "services-page-client.tsx"), "utf8");
  const datePicker = readFileSync(join(process.cwd(), "src", "components", "ui", "production-date-picker.tsx"), "utf8");
  const productionSelect = readFileSync(join(process.cwd(), "src", "components", "ui", "production-select.tsx"), "utf8");
  const globals = readFileSync(join(process.cwd(), "src", "app", "globals.css"), "utf8");
  const readOnlyDetails = page.slice(page.indexOf("function ReadOnlyServiceDetails"), page.indexOf("type ServiceListItem"));
  const serviceBlockEditor = page.slice(page.indexOf("function ServiceBlockEditor"), page.indexOf("function ReadOnlyServiceDetails"));
  const deleteConfirmationModal = page.slice(page.indexOf('<Dialog open={deleteConfirmOpen}'), page.indexOf('{pendingServiceSave'));
  const serviceRowMenu = page.slice(page.indexOf('<DropdownMenuContent align="end" side="left" sideOffset={8} className="workspace-content-light w-40'), page.indexOf('</DropdownMenuContent>', page.indexOf('<DropdownMenuContent align="end" side="left" sideOffset={8} className="workspace-content-light w-40')));

  assert.match(route, /blocks:\s*\{[\s\S]*?orderBy:\s*\{\s*order:\s*"asc"/);
  assert.match(page, /Service flow/);
  assert.match(page, /function ServiceBlockEditor/);
  assert.match(serviceBlockEditor, /grid gap-3 md:grid-cols-2/);
  assert.match(serviceBlockEditor, /space-y-2/);
  assert.doesNotMatch(serviceBlockEditor, /border-t border-\[var\(--rule-default\)\]/);
  assert.match(serviceBlockEditor, /const autoSizeTextarea/);
  assert.match(serviceBlockEditor, /rows=\{2\}/);
  assert.match(serviceBlockEditor, /service-block-textarea min-h-14/);
  assert.match(serviceBlockEditor, /resize-none overflow-hidden/);
  assert.match(serviceBlockEditor, /style=\{\{ backgroundColor: "transparent", boxShadow: "none" \}\}/);
  assert.match(serviceBlockEditor, /border border-\[var\(--border-default\)\]/);
  assert.match(page, /hover:border-\[var\(--state-danger\)\] hover:text-\[var\(--state-danger\)\]/);
  assert.match(page, /TeamMemberPicker/);
  assert.equal((page.match(/<TeamMemberPicker/g) ?? []).length, 2);
  assert.match(page, /blocks=\{service\.blocks\}/);
  assert.match(page, /services-register ui-surface-elevated/);
  assert.match(page, /sm:flex-row sm:flex-wrap sm:items-center sm:justify-between/);
  assert.doesNotMatch(page, /<h2 className="text-base font-semibold text-\[var\(--text-primary\)\]">Service register<\/h2>/);
  assert.match(page, /const isRefreshingServices = servicesQuery\.isFetching;/);
  assert.match(page, /const selectionStateLabel = allFilteredServicesSelected \? "All" : selectedFilteredServiceCount > 0 \? "Partial" : "None";/);
  assert.match(page, /selectionCheckboxRef\.current\.indeterminate = selectedFilteredServiceCount > 0 && !allFilteredServicesSelected;/);
  assert.match(page, /function toggleFilteredServiceSelection\(\)/);
  assert.match(page, /grid-cols-\[56px_minmax\(0,1\.2fr\)/);
  assert.doesNotMatch(page, /<span>\{selectionStateLabel\}<\/span>/);
  assert.match(globals, /\.ui-checkbox:indeterminate/);
  assert.match(globals, /d='M4 8h8'/);
  assert.match(page, /hover:text-\[var\(--action-primary-bg\)\]/);
  assert.match(page, /isRefreshingServices \? "h-4 w-4 animate-spin" : "h-4 w-4"/);
  assert.match(page, /\{filteredServices\.length\} of \{services\.length\} services/);
  assert.match(page, /text-sm leading-6 text-\[var\(--text-secondary\)\] md:text-base/);
  assert.match(page, /<X className="h-4 w-4" aria-hidden="true" \/>\s*Clear filters/);
  assert.match(page, /text-\[var\(--text-secondary\)\] hover:text-\[var\(--state-danger\)\]/);
  assert.match(page, /aria-label=\{`Delete \$\{selectedServiceIds\.length\} selected service/);
  assert.match(page, /function AnimatedTrashBinIcon\(\)/);
  assert.match(page, /className="h-5 w-5"/);
  assert.match(page, /group-hover:-translate-y-1 group-hover:-rotate-12/);
  assert.match(page, /group inline-flex h-10 w-10 items-center justify-center rounded-md bg-transparent text-\[var\(--text-danger\)\] disabled:opacity-50/);
  assert.doesNotMatch(page, /<DialogContent className="relative max-w-md">/);
  assert.match(deleteConfirmationModal, /aria-label="Close delete confirmation"/);
  assert.doesNotMatch(deleteConfirmationModal, />\s*Cancel\s*<\/button>/);
  assert.match(deleteConfirmationModal, /border border-\[var\(--border-default\)\] bg-transparent.*text-\[var\(--text-secondary\)\].*hover:border-transparent hover:bg-\[var\(--state-danger\)\] hover:text-\[var\(--action-primary-ink\)\]/);
  assert.match(deleteConfirmationModal, /active:border-transparent active:bg-\[var\(--state-danger\)\] active:text-\[var\(--action-primary-ink\)\]/);
  assert.match(page, /grid-cols-\[2rem_minmax\(10rem,0\.8fr\)_minmax\(12rem,1\.2fr\)\]/);
  assert.match(page, /service\.blocks\.map\(\(block, index\)/);
  assert.match(page, /String\(index \+ 1\)\.padStart\(2, "0"\)/);
  assert.doesNotMatch(page, /<ul className="divide-y divide-\[var\(--rule-default\)\]">/);
  assert.match(page, /relative before:absolute before:inset-y-0 before:left-0 before:w-1 before:bg-\[var\(--action-primary-bg\)\]/);
  assert.match(page, /const followsExpandedService = index > 0 && filteredServices\[index - 1\]\?\.id === expandedServiceId;/);
  assert.match(page, /followsExpandedService \? "border-t border-\[var\(--rule-default\)\]" : ""/);
  assert.doesNotMatch(page, /border-l-4 border-\[var\(--action-primary-bg\)\]/);
  assert.doesNotMatch(page, /className="border-t border-\[var\(--border-default\)\] bg-\[var\(--surface-panel\)\]"/);
  assert.doesNotMatch(page, /border-b border-\[var\(--rule-default\)\] bg-\[var\(--surface-panel-strong\)\] px-4 py-4 md:flex-row/);
  assert.match(page, /if \(status === ServiceStatus\.READY\) return "var\(--state-success\)";/);
  assert.match(page, /if \(status === ServiceStatus\.DRAFT\) return "var\(--state-danger\)";/);
  assert.match(page, /className=\{`group \$\{/);
  assert.match(page, /opacity-0 group-hover:opacity-100 group-focus-within:opacity-100 focus:opacity-100/);
  assert.match(page, /isEditing \|\| service\.status === ServiceStatus\.DRAFT \? \(/);
  assert.match(serviceRowMenu, /service-row-menu-action-edit[^\"]*!text-\[var\(--text-primary\)\][^\"]*\[&_svg\]:!text-current/);
  assert.match(serviceRowMenu, /service\.status === ServiceStatus\.DRAFT/);
  assert.match(serviceRowMenu, /<Check className="h-3\.5 w-3\.5" \/>\} Mark ready/);
  assert.match(serviceRowMenu, /service-row-menu-action-delete[^\"]*!text-\[var\(--text-primary\)\][^\"]*\[&_svg\]:!text-current/);
  assert.doesNotMatch(page, /rounded-md border border-\[var\(--border-default\)\] text-\[var\(--text-primary\)\] hover:bg-\[var\(--surface-panel-alt\)\]/);
  assert.doesNotMatch(page, /<span>Sermon verse<\/span>/);
  assert.doesNotMatch(page, /service\.sermonVerse \|\| "No sermon verse"/);
  assert.match(page, /const \[editServiceDate, setEditServiceDate\] = useState\(""\);/);
  assert.match(page, /const \[editMinistryPresetCode, setEditMinistryPresetCode\] = useState\(""\);/);
  assert.match(page, /serviceDate: new Date\(serviceDate\)\.toISOString\(\)/);
  assert.match(page, /const service = await apiFetch<ServiceRecord>\(/);
  assert.match(page, /<ProductionDatePicker/);
  assert.equal((page.match(/<ProductionDatePicker/g) ?? []).length, 4);
  assert.match(page, /<ProductionDatePicker\s+label="Service date"\s+value=\{editServiceDate\}/);
  assert.match(page, /<ProductionSelect label="Assigned ministry" value=\{editMinistryPresetCode\}/);
  assert.match(page, /labelClassName="mb-1 block text-sm font-semibold text-\[var\(--text-primary\)\]"/);
  assert.doesNotMatch(page, />Edit service<\/h3>/);
  assert.doesNotMatch(page, /Edit the fields copied into this service/);
  assert.doesNotMatch(page, /type="date"/);
  assert.doesNotMatch(page, /<span className="mb-1.5 block">Service date<\/span>/);
  assert.doesNotMatch(page, /<span className="mb-1.5 block text-xs font-medium text-\[var\(--text-muted\)\]">Ministry<\/span>/);
  assert.match(datePicker, /Popover\.Content/);
  assert.doesNotMatch(datePicker, /DialogContent/);
  assert.match(datePicker, /side="bottom"/);
  assert.match(productionSelect, /bg-transparent.*text-\[var\(--text-primary\)\]/);
  assert.match(productionSelect, /hover:bg-\[var\(--palette-primary-focus\)\] hover:text-\[var\(--text-primary\)\]/);
  assert.match(productionSelect, /focus:\*\*:!text-\[var\(--text-primary\)\]/);
  assert.match(productionSelect, /data-\[state=checked\]:bg-\[var\(--action-primary-bg\)\] data-\[state=checked\]:text-\[var\(--action-primary-ink\)\]/);
  assert.match(productionSelect, /data-\[state=checked\]:hover:bg-\[var\(--action-primary-bg\)\] data-\[state=checked\]:hover:text-\[var\(--action-primary-ink\)\]/);
  assert.match(page, /status: ServiceStatus\.READY/);
  assert.match(page, /Mark ready/);
  assert.doesNotMatch(readOnlyDetails, /<dl/);
  assert.match(readOnlyDetails, /text-right/);
  assert.match(readOnlyDetails, /formatServantDisplayName/);
  assert.doesNotMatch(readOnlyDetails, /text-\[var\(--text-accent\)\]/);
  assert.doesNotMatch(page, /<ServiceFormFields/);
  assert.doesNotMatch(page, /<h4[^>]*>Bible verses<\/h4>/);
  assert.doesNotMatch(page, /<h3>Servants<\/h3>/);
  assert.doesNotMatch(page, /<h3>Hymnals<\/h3>/);
}
