ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'BACKGROUND_IMAGE_GENERATE';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'BACKGROUND_VIDEO_GENERATE';

ALTER TYPE "OutputType" ADD VALUE IF NOT EXISTS 'BACKGROUND_IMAGE';
ALTER TYPE "OutputType" ADD VALUE IF NOT EXISTS 'BACKGROUND_VIDEO';
