import { runPrivateOutputStorageTests } from "./lib/private-output-storage.test.ts";
import { runRateLimitTests } from "./lib/rate-limit.test.ts";
import { runSecurityContextTests } from "./lib/security-context.test.ts";
import { runProxyTests } from "./proxy.test.ts";
import { runMediaGenerationTests } from "./features/media-generation/media-generation.test.ts";
import { runBackgroundOutputRetentionTests } from "./features/media-generation/server/background-output-retention.test.ts";
import { runOpenAIBackgroundRemovalTests } from "./features/media-generation/server/openai-background-removal.test.ts";
import { runPAPApiErrorTests } from "./features/pap/server/pap-api-errors.test.ts";
import { runPAPDeviceNameTests } from "./features/pap/pap-device-name.test.ts";
import { runResizeImageTests } from "./lib/resize-image.test.ts";
import { runServiceRecordTests } from "./lib/service-records.test.ts";
import { runServantDirectoryTests } from "./lib/servant-directory.test.ts";
import { runServicesSecurityTests } from "./lib/services-security.test.ts";
import { runServiceTextAnalysisTests } from "./lib/service-text-analysis.test.ts";
import { runServiceBlockTests } from "./lib/service-blocks.test.ts";
import { runServiceDisplayTests } from "./lib/service-display.test.ts";
import { runProgramBlockTypeTests } from "./lib/program-block-types.test.ts";
import { runTemplateFieldTests } from "./lib/template-fields.test.ts";
import { runServiceReadinessTests } from "./lib/service-readiness.test.ts";
import { runSettingsPresetTests } from "./lib/settings-presets.test.ts";
import { runTemplateBlockTests } from "./lib/template-blocks.test.ts";
import { runWorkspaceIntegrationTests } from "./lib/workspace-integrations.test.ts";
import { runWorkspaceModulesTests } from "./lib/workspace-modules.test.ts";
import { runWorkspaceAuthTests } from "./lib/workspace-auth.test.ts";
import { runWorkspaceSlugTests } from "./lib/workspace-slug.test.ts";
import { runUploadSecurityTests } from "./lib/upload-security.test.ts";
import { runContentSecurityPolicyTests } from "./lib/content-security-policy.test.ts";
import { runAuthRedirectTests } from "./lib/auth-redirect.test.ts";
import { runLocalAuthConfigTests } from "./lib/local-auth-config.test.ts";
import { runMembershipSectionUiTests } from "./components/membership-section-ui.test.ts";
import { runWorkspaceShellTests } from "./lib/workspace-shell.test.ts";
import { runFeedbackTests } from "./lib/feedback.test.ts";
import { runWorkspaceRouteTests } from "./lib/workspace-route.test.ts";
import { runWorkspaceMembersRouteTests } from "./lib/workspace-members-route.test.ts";
import { runTransposeParserTests } from "./lib/transpose-parser.test.ts";
import { runExtractorAiTests } from "./lib/extractor-ai.test.ts";
import { runOAuthClientBoundaryTests, runOAuthSecretHygieneTests } from "./lib/oauth-secret-hygiene.test.ts";
import { runSettingsNavigationTests } from "./lib/settings-navigation.test.ts";
import { runTemplatePdfImportTests } from "./lib/template-pdf-import.test.ts";
import { runTemplateBlockKindTests } from "./lib/template-block-kinds.test.ts";
import { runServiceTemplateRenderingTests } from "./lib/service-template-rendering.test.ts";
import { runTeamMemberPickerTests } from "./lib/team-member-picker.test.ts";
import { runDeploymentBuildTests } from "./lib/deployment-build.test.ts";
import packageJson from "../package.json" with { type: "json" };

runSecurityContextTests();
runPrivateOutputStorageTests();
runRateLimitTests();
runProxyTests();
runMediaGenerationTests();
runBackgroundOutputRetentionTests();
await runOpenAIBackgroundRemovalTests();
runPAPApiErrorTests();
runPAPDeviceNameTests();
runResizeImageTests();
runServiceRecordTests();
runServantDirectoryTests();
runServicesSecurityTests();
runServiceTextAnalysisTests();
runServiceBlockTests();
runServiceDisplayTests();
runProgramBlockTypeTests();
runTemplateFieldTests();
runServiceReadinessTests();
runSettingsPresetTests();
runTemplateBlockTests();
runWorkspaceIntegrationTests();
runWorkspaceModulesTests();
runWorkspaceAuthTests();
runWorkspaceSlugTests();
await runUploadSecurityTests();
await runContentSecurityPolicyTests();
runAuthRedirectTests();
runLocalAuthConfigTests();
runMembershipSectionUiTests();
runWorkspaceShellTests();
runFeedbackTests();
runWorkspaceRouteTests();
runWorkspaceMembersRouteTests();
await runTransposeParserTests();
await runExtractorAiTests();
runOAuthSecretHygieneTests();
runOAuthClientBoundaryTests();
runSettingsNavigationTests();
runTemplatePdfImportTests();
runTemplateBlockKindTests();
runServiceTemplateRenderingTests();
runTeamMemberPickerTests();
runDeploymentBuildTests();

if (packageJson.scripts["vercel-build"] !== "node scripts/vercel-build.mjs") {
  throw new Error("vercel-build must run the deployment build script");
}

console.log("security tests passed");
